AWSTemplateFormatVersion: '2010-09-09'
Description: UrbanGrow Full Stack with VPC, Microsoft AD, and Windows VDI (AWS Academy Safe)

Parameters:
  GroupName:
    Type: String
    Default: Group01

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 KeyPair

  DirectoryAdminPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Password for AD Administrator

Resources:

  # ----------------------------
  # VPC & SUBNETS
  # ----------------------------
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub urbangrow-vpc-${GroupName}

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.10.0/24
      AvailabilityZone: !Select [0, !GetAZs '']

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: !Select [1, !GetAZs '']

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # ----------------------------
  # DIRECTORY SERVICE (AD)
  # ----------------------------
  DirectoryService:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      Name: urbangrow.local
      Password: !Ref DirectoryAdminPassword
      Edition: Standard
      VpcSettings:
        VpcId: !Ref VPC
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2

  # ----------------------------
  # SECURITY GROUPS
  # ----------------------------
  VDISecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow RDP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0

  # ----------------------------
  # WINDOWS VDI INSTANCE
  # ----------------------------
  VDIInstance:
    Type: AWS::EC2::Instance
    DependsOn: DirectoryService
    Properties:
      InstanceType: t3.medium
      ImageId: ami-06777e7ef7441deff   # Windows Server 2025 Base
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref VDISecurityGroup

      # ⚠️ Use EXISTING instance profile (AWS Academy)
      IamInstanceProfile: LabInstanceProfile

      UserData:
        Fn::Base64: !Sub |
          <powershell>
          $domain = "urbangrow.local"
          $password = "${DirectoryAdminPassword}" | ConvertTo-SecureString -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ("Administrator", $password)

          Add-Computer -DomainName $domain -Credential $cred -Force -Restart
          </powershell>

      Tags:
        - Key: Name
          Value: !Sub urbangrow-vdi-${GroupName}

Outputs:
  VDIInstancePublicIP:
    Description: Windows VDI Public IP
    Value: !GetAtt VDIInstance.PublicIp

  DirectoryDNS:
    Description: Active Directory DNS IPs
    Value: !Join [", ", !GetAtt DirectoryService.DnsIpAddresses]
