AWSTemplateFormatVersion: '2010-09-09'
Description: UrbanGrow VPC + Windows VDI using EXISTING Microsoft AD (AWS Academy Safe)

Parameters:
  GroupName:
    Type: String
    Default: Group01

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 KeyPair

  DirectoryAdminPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Password for AD Administrator

  ExistingDirectoryId:
    Type: String
    Default: d-906619acf0
    Description: Existing AWS Managed Microsoft AD ID

  ADDnsIp1:
    Type: String
    Description: First DNS IP of existing AD

  ADDnsIp2:
    Type: String
    Description: Second DNS IP of existing AD

Resources:

  # ----------------------------
  # VPC & SUBNETS
  # ----------------------------
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub urbangrow-vpc-${GroupName}

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # ----------------------------
  # SECURITY GROUP
  # ----------------------------
  VDISecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow RDP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0

  # ----------------------------
  # WINDOWS VDI INSTANCE
  # ----------------------------
  VDIInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: ami-06777e7ef7441deff   # Windows Server
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref VDISecurityGroup
      IamInstanceProfile: LabInstanceProfile

      UserData:
        Fn::Base64: !Sub |
          <powershell>
          # Set DNS to existing AD
          $adapter = Get-NetAdapter | Where-Object {$_.Status -eq "Up"}
          Set-DnsClientServerAddress -InterfaceIndex $adapter.InterfaceIndex `
            -ServerAddresses ("${ADDnsIp1}", "${ADDnsIp2}")

          $password = "${DirectoryAdminPassword}" | ConvertTo-SecureString -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ("Administrator", $password)

          Add-Computer `
            -DomainName "urbangrow.local" `
            -Credential $cred `
            -Force `
            -Restart
          </powershell>

      Tags:
        - Key: Name
          Value: !Sub urbangrow-vdi-${GroupName}

Outputs:
  VDIInstancePublicIP:
    Description: Windows VDI Public IP
    Value: !GetAtt VDIInstance.PublicIp

  UsedDirectoryId:
    Description: Existing AD Directory ID
    Value: !Ref ExistingDirectoryId
