AWSTemplateFormatVersion: '2010-09-09'
Description: UrbanGrow insecure lab environment with MongoDB, Web Server, and optional VDI

Parameters:
  GroupName:
    Type: String
  GroupSize:
    Type: Number
    Default: 2
    AllowedValues: [2, 3]
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Conditions:
  CreateVDI: !Equals [!Ref GroupSize, 3]

Resources:

  # -------------------- Networking -------------------- #
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  DefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

  # -------------------- MongoDB -------------------- #
  MongoSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Insecure MongoDB SG
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          CidrIp: 0.0.0.0/0

  MongoInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      SubnetId: !Ref PublicSubnet
      KeyName: !Ref KeyName
      SecurityGroupIds: [!Ref MongoSG]
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          set -xe

          cat <<EOF > /etc/yum.repos.d/mongodb-org-7.0.repo
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/7.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-7.0.asc
          EOF

          dnf install -y mongodb-org
          sed -i 's/bindIp: 127.0.0.1/bindIp: 0.0.0.0/' /etc/mongod.conf
          systemctl enable mongod
          systemctl restart mongod

          until ss -lnt | grep 27017; do sleep 5; done

  # -------------------- Web Server -------------------- #
  WebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Insecure Web SG
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnet
      KeyName: !Ref KeyName
      SecurityGroupIds: [!Ref WebSG]
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          dnf install -y httpd php php-mongodb
          systemctl enable httpd
          systemctl start httpd

  # -------------------- VDI (Optional) -------------------- #
  VDISG:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateVDI
    Properties:
      GroupDescription: Insecure RDP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0

  VDIInstance:
    Type: AWS::EC2::Instance
    Condition: CreateVDI
    Properties:
      InstanceType: t3.medium
      SubnetId: !Ref PublicSubnet
      KeyName: !Ref KeyName
      SecurityGroupIds: [!Ref VDISG]
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-windows-latest/Windows_Server-2022-English-Full-Base}}"

Outputs:
  MongoServerPublicIP:
    Value: !GetAtt MongoInstance.PublicIp
  WebServerPublicIP:
    Value: !GetAtt WebInstance.PublicIp
