AWSTemplateFormatVersion: '2010-09-09'
Description: >
  UrbanGrow Group Project.
  Insecure demo environment with Web Server, MongoDB on EC2,
  and optional Windows VDI instance.

Parameters:
  GroupName:
    Type: String
  GroupSize:
    Type: Number
    Default: 2
    AllowedValues: [2, 3]
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Conditions:
  CreateVDI: !Equals [!Ref GroupSize, 3]

# ------------------------------------------------------------
# Networking
# ------------------------------------------------------------
Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub urbangrow-vpc-${GroupName}

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs '']

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

# ------------------------------------------------------------
# MongoDB EC2
# ------------------------------------------------------------

  MongoSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MongoDB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          CidrIp: 0.0.0.0/0

  MongoInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      ImageId: ami-00ca32bbc84273381
      SubnetId: !Ref PublicSubnet1
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MongoSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          set -e

          cat <<EOF > /etc/yum.repos.d/mongodb-org-7.0.repo
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/7.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-7.0.asc
          EOF

          dnf install -y mongodb-org
          sed -i 's/bindIp: 127.0.0.1/bindIp: 0.0.0.0/' /etc/mongod.conf
          systemctl enable mongod
          systemctl start mongod

      Tags:
        - Key: Name
          Value: !Sub mongo-${GroupName}

# ------------------------------------------------------------
# Web Server EC2
# ------------------------------------------------------------

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebInstance:
    Type: AWS::EC2::Instance
    DependsOn: MongoInstance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-00ca32bbc84273381
      SubnetId: !Ref PublicSubnet1
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf install -y httpd php php-cli
          systemctl start httpd
          systemctl enable httpd

          cat <<EOF > /var/www/html/index.php
          <?php
          echo "MongoDB Server: ${MongoInstance.PublicIp}";
          ?>
          EOF

      Tags:
        - Key: Name
          Value: !Sub web-${GroupName}

# ------------------------------------------------------------
# Optional VDI (Student 3)
# ------------------------------------------------------------

  VDISecurityGroup:
    Condition: CreateVDI
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow RDP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0

  VDIInstance:
    Condition: CreateVDI
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: ami-0efee5160a1079475
      SubnetId: !Ref PublicSubnet1
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref VDISecurityGroup

# ------------------------------------------------------------
# Outputs
# ------------------------------------------------------------
Outputs:
  WebPublicIP:
    Value: !GetAtt WebInstance.PublicIp

  MongoPublicIP:
    Value: !GetAtt MongoInstance.PublicIp
    Export:
      Name: MongoServerPublicIP
