AWSTemplateFormatVersion: '2010-09-09'
Description: >
  UrbanGrow Group Project.
  Insecure demo environment with Web, MongoDB, Windows VDI,
  using NEW AWS Managed Microsoft AD.
  Uses existing IAM Instance Profile for VDI domain join.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: urbangrow-vpc-Group01

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.10.0/24
      AvailabilityZone: !Select [0, !GetAZs '']

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.11.0/24

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  MongoSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Insecure MongoDB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          CidrIp: 0.0.0.0/0

  MongoInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      ImageId: ami-00ca32bbc84273381
      SubnetId: !Ref PublicSubnet1
      KeyName: your-ec2-keypair-name
      SecurityGroupIds: [!Ref MongoSG]
      UserData:
        Fn::Base64: |
          #!/bin/bash
          dnf install -y mongodb-org
          systemctl enable mongod
          systemctl start mongod
          sed -i 's/bindIp: 127.0.0.1/bindIp: 0.0.0.0/' /etc/mongod.conf
          systemctl restart mongod

  WebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Insecure HTTP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-00ca32bbc84273381
      SubnetId: !Ref PublicSubnet1
      KeyName: your-ec2-keypair-name
      SecurityGroupIds: [!Ref WebSG]
      UserData:
        Fn::Base64: |
          #!/bin/bash
          dnf install -y httpd
          systemctl enable httpd
          systemctl start httpd

  NewDirectory:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      Name: corp.urbangrow.local
      Password: YourStrongPassword123!
      VpcSettings:
        VpcId: !Ref VPC
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Edition: Standard
      ShortName: UrbanGrow

  VDISG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Insecure RDP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0

  VDIInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: /aws/service/ami-windows-latest/Windows_Server-2022-English-Full-Base
      SubnetId: !Ref PublicSubnet1
      KeyName: your-ec2-keypair-name
      SecurityGroupIds: [!Ref VDISG]
      IamInstanceProfile: your-existing-instance-profile
      UserData:
        Fn::Base64:
          !Sub
            - |
              <powershell>
              $adapter = Get-NetAdapter | Where-Object {$_.Status -eq "Up"}
              Set-DnsClientServerAddress `
                -InterfaceIndex $adapter.InterfaceIndex `
                -ServerAddresses ("${DnsIp1}", "${DnsIp2}")

              $pw = ConvertTo-SecureString "YourStrongPassword123!" -AsPlainText -Force
              $cred = New-Object System.Management.Automation.PSCredential ("Administrator", $pw)

              Add-Computer `
                -DomainName "corp.urbangrow.local" `
                -Credential $cred `
                -Restart `
                -Force
              </powershell>
            - DnsIp1: !Select [0, !GetAtt NewDirectory.DnsIpAddresses]
              DnsIp2: !Select [1, !GetAtt NewDirectory.DnsIpAddresses]

Outputs:
  WebServerPublicIP:
    Description: Public IP of the Web Server
    Value: !GetAtt WebInstance.PublicIp

  MongoServerPublicIP:
    Description: Public IP of the MongoDB Server
    Value: !GetAtt MongoInstance.PublicIp

  NewDirectoryId:
    Description: New AWS Managed Microsoft AD Directory ID
    Value: !Ref NewDirectory

  DirectoryDnsIp1:
    Description: Primary DNS IP of new AD
    Value: !Select [0, !GetAtt NewDirectory.DnsIpAddresses]

  DirectoryDnsIp2:
    Description: Secondary DNS IP of new AD
    Value: !Select [1, !GetAtt NewDirectory.DnsIpAddresses]

  VDIInstanceId:
    Description: Instance ID of the Windows VDI
    Value: !Ref VDIInstance
